(()=>{'use strict';const $=id=>document.getElementById(id),C=window.ALBION_CONTENT,Q=window.ALBION_QUIZ||[];const squad=C.squad;
function countdown(){const t=new Date('2026-08-23T14:00:00+01:00')-new Date(),e=$('countdown');if(!e)return;if(t<=0){e.textContent='Matchday';return}const d=Math.floor(t/864e5),h=Math.floor(t%864e5/36e5),m=Math.floor(t%36e5/6e4);e.innerHTML=`<b>${d}</b> days <b>${h}</b> hrs <b>${m}</b> mins`;}
const formations={'4-2-3-1':['GK','RB','CB','CB','LB','DM','DM','RW','AM','LW','ST'],'4-3-3':['GK','RB','CB','CB','LB','CM','CM','CM','RW','ST','LW'],'3-4-2-1':['GK','CB','CB','CB','RWB','CM','CM','LWB','AM','AM','ST']};
const preferred={GK:'Bart Verbruggen',RB:'Jack Hinshelwood',CB:'Lewis Dunk',LB:'Maxim De Cuyper',DM:'Carlos Baleba',CM:'Mats Wieffer',RWB:'Ferdi Kadioglu',LWB:'Kaoru Mitoma',RW:'Yankuba Minteh',AM:'Georginio Rutter',LW:'Kaoru Mitoma',ST:'Danny Welbeck'};
function options(role){const groups={GK:['Goalkeeper'],RB:['Defender','Midfielder'],LB:['Defender','Midfielder'],CB:['Defender'],DM:['Midfielder'],CM:['Midfielder'],RWB:['Defender','Midfielder'],LWB:['Defender','Midfielder'],RW:['Midfielder','Forward'],LW:['Midfielder','Forward'],AM:['Midfielder','Forward'],ST:['Forward']};return squad.filter(p=>groups[role].includes(p.position));}
function renderPitch(saved){const form=$('formation').value,roles=formations[form],pitch=$('pitch');pitch.innerHTML='';roles.forEach((r,i)=>{const cell=document.createElement('label');cell.className='player-slot';cell.innerHTML=`<span>${r}</span><select data-slot="${i}"><option value="">Select player</option>${options(r).map(p=>`<option>${p.name}</option>`).join('')}</select>`;pitch.appendChild(cell);const val=saved?.[i]||'';cell.querySelector('select').value=val;});pitch.querySelectorAll('select').forEach(s=>s.addEventListener('change',saveXI));}
function predicted(){const used=new Set(),vals=[];formations[$('formation').value].forEach(r=>{let n=preferred[r];if(used.has(n)||!options(r).some(p=>p.name===n))n=options(r).find(p=>!used.has(p.name))?.name||'';used.add(n);vals.push(n)});renderPitch(vals);saveXI();}
function saveXI(){const vals=[...document.querySelectorAll('#pitch select')].map(s=>s.value);localStorage.setItem('albionXI',JSON.stringify({f:$('formation').value,v:vals}));const d=vals.filter(Boolean);$('xiMessage').textContent=d.length===11?(new Set(d).size===11?'Your XI is complete and saved.':'Choose eleven different players.'):`${d.length}/11 positions selected.`;}
function initXI(){let saved;try{saved=JSON.parse(localStorage.getItem('albionXI'))}catch{}if(saved?.f)$('formation').value=saved.f;renderPitch(saved?.v);$('formation').addEventListener('change',()=>renderPitch());$('loadPredicted').onclick=predicted;$('clearXI').onclick=()=>{localStorage.removeItem('albionXI');renderPitch();$('xiMessage').textContent='Line-up cleared.'};}
function renderFixtures(){const q=$('fixtureSearch').value.toLowerCase(),v=$('venueFilter').value;const list=C.fixtures.filter(f=>(v==='all'||f.venue===v)&&f.opponent.toLowerCase().includes(q));$('fixtureList').innerHTML=list.map(f=>`<article class="fixture-item"><div><b>${f.date}</b><small>Premier League</small></div><div><strong>${f.venue==='H'?'Albion v '+f.opponent:f.opponent+' v Albion'}</strong><small>${f.venue==='H'?'Amex Stadium':'Away'}</small></div></article>`).join('');}
let current=[];function newQuiz(){current=[...Q].sort(()=>Math.random()-.5).slice(0,5);$('quizContainer').innerHTML=current.map((q,i)=>`<fieldset class="quiz-question"><legend>${i+1}. ${q.question}</legend>${q.options.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${o}</label>`).join('')}</fieldset>`).join('');$('quizResult').textContent='';}function checkQuiz(){let s=0;current.forEach((q,i)=>{const a=document.querySelector(`input[name=q${i}]:checked`);if(a&&+a.value===q.answer)s++});$('quizResult').textContent=`You scored ${s}/5.`;}
function predictor(){const names=squad.filter(p=>p.position!=='Goalkeeper').map(p=>p.name);$('firstScorer').innerHTML='<option>No scorer</option>'+names.map(n=>`<option>${n}</option>`).join('');$('motm').innerHTML=squad.map(p=>`<option>${p.name}</option>`).join('');$('savePrediction').onclick=()=>{const text=`Albion ${$('homeScore').value}-${$('awayScore').value} Aston Villa · First scorer: ${$('firstScorer').value} · Player of the match: ${$('motm').value}`;localStorage.setItem('albionPrediction',text);$('predictionSummary').textContent=text};$('predictionSummary').textContent=localStorage.getItem('albionPrediction')||'Make and save your prediction.';}
function facts(){const show=()=>{$('factText').textContent=C.facts[Math.floor(Math.random()*C.facts.length)]};show();$('newFact').onclick=show;}
function weather(){const e=$('weatherPanel'),days=(new Date('2026-08-23')-new Date())/864e5;if(days>14){e.innerHTML='<p>Forecasts are not reliable this far ahead. This panel will activate closer to the Aston Villa match.</p>';return}fetch('https://api.open-meteo.com/v1/forecast?latitude=50.8616&longitude=-0.0837&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Europe%2FLondon').then(r=>r.json()).then(d=>{const i=d.daily.time.indexOf('2026-08-23');e.innerHTML=i<0?'<p>Matchday forecast not available yet.</p>':`<p><b>${Math.round(d.daily.temperature_2m_max[i])}°C</b> high · ${Math.round(d.daily.precipitation_probability_max[i])}% rain chance</p>`}).catch(()=>e.innerHTML='<p>Weather temporarily unavailable.</p>');}
function ui(){$('menuToggle').onclick=()=>$('navLinks').classList.toggle('open');$('fixtureSearch').oninput=renderFixtures;$('venueFilter').onchange=renderFixtures;$('newQuiz').onclick=newQuiz;$('checkQuiz').onclick=checkQuiz;$('winConfetti').onclick=()=>{$('celebration').classList.add('show');for(let i=0;i<50;i++){const x=document.createElement('i');x.className='confetti';x.style.left=Math.random()*100+'%';x.style.animationDelay=Math.random()+'s';x.textContent=Math.random()>.4?'🕊️':'◆';$('celebration').appendChild(x)}};$('closeCelebration').onclick=()=>{$('celebration').classList.remove('show');document.querySelectorAll('.confetti').forEach(x=>x.remove())};}
countdown();setInterval(countdown,60000);initXI();renderFixtures();newQuiz();predictor();facts();weather();ui();})();