window.ENGLAND_CONTENT = {
  squad: [
    {name:'Jordan Pickford',position:'Goalkeeper',club:'Everton'},
    {name:'Dean Henderson',position:'Goalkeeper',club:'Crystal Palace'},
    {name:'James Trafford',position:'Goalkeeper',club:'Burnley'},
    {name:'Ezri Konsa',position:'Defender',club:'Aston Villa'},
    {name:"Nico O'Reilly",position:'Defender',club:'Manchester City'},
    {name:'John Stones',position:'Defender',club:'Manchester City'},
    {name:'Marc Guéhi',position:'Defender',club:'Crystal Palace'},
    {name:'Trevoh Chalobah',position:'Defender',club:'Chelsea'},
    {name:'Dan Burn',position:'Defender',club:'Newcastle United'},
    {name:'Reece James',position:'Defender',club:'Chelsea'},
    {name:'Djed Spence',position:'Defender',club:'Tottenham Hotspur'},
    {name:'Jarell Quansah',position:'Defender',club:'Liverpool'},
    {name:'Declan Rice',position:'Midfielder',club:'Arsenal'},
    {name:'Elliot Anderson',position:'Midfielder',club:'Nottingham Forest'},
    {name:'Jude Bellingham',position:'Midfielder',club:'Real Madrid'},
    {name:'Jordan Henderson',position:'Midfielder',club:'Ajax'},
    {name:'Kobbie Mainoo',position:'Midfielder',club:'Manchester United'},
    {name:'Morgan Rogers',position:'Midfielder',club:'Aston Villa'},
    {name:'Bukayo Saka',position:'Forward',club:'Arsenal'},
    {name:'Harry Kane',position:'Forward',club:'Bayern Munich'},
    {name:'Marcus Rashford',position:'Forward',club:'Manchester United'},
    {name:'Anthony Gordon',position:'Forward',club:'Newcastle United'},
    {name:'Ollie Watkins',position:'Forward',club:'Aston Villa'},
    {name:'Noni Madueke',position:'Forward',club:'Chelsea'},
    {name:'Eberechi Eze',position:'Forward',club:'Crystal Palace'},
    {name:'Ivan Toney',position:'Forward',club:'Al-Ahli'}
  ],
  scorers: ['Ezri Konsa',"Nico O'Reilly",'John Stones','Marc Guéhi','Trevoh Chalobah','Dan Burn','Reece James','Djed Spence','Jarell Quansah','Declan Rice','Elliot Anderson','Jude Bellingham','Jordan Henderson','Kobbie Mainoo','Morgan Rogers','Bukayo Saka','Harry Kane','Marcus Rashford','Anthony Gordon','Ollie Watkins','Noni Madueke','Eberechi Eze','Ivan Toney'],
  recentForm: ['W','W','W','D','W'],
  quotes: ['Believe until the final whistle.','One team. One dream. Three Lions.','Play for the badge and sing for the shirt.','Every great run needs one more win.','Ninety minutes can create a lifetime of memories.'],
  facts: [
    'England won the 1966 men’s World Cup at Wembley after extra time against West Germany.',
    'Geoff Hurst remains the only player to score a hat-trick in a men’s World Cup final.',
    'Gary Lineker won the Golden Boot at the 1986 men’s World Cup in Mexico.',
    'England reached men’s World Cup semi-finals in 1966, 1990 and 2018.',
    'England’s first men’s World Cup appearance came in Brazil in 1950.',
    'England’s first World Cup penalty shoot-out win came against Colombia in 2018.',
    'Bobby Charlton scored two goals in England’s 1966 semi-final win over Portugal.',
    'England’s 6-1 win against Panama in 2018 is their biggest men’s World Cup win.',
    'Martin Peters scored England’s second goal in the 1966 World Cup final.',
    'Gordon Banks kept clean sheets in England’s 1966 knockout wins before the final.',
    'David Platt scored a famous extra-time volley against Belgium at Italia 90.',
    'Michael Owen scored his famous solo goal against Argentina at France 98.',
    'England beat Denmark 3-0 in the 2002 World Cup round of 16.',
    'David Beckham scored the penalty that beat Argentina at the 2002 World Cup.',
    'England lost on penalties to Portugal at both the 2006 World Cup and Euro 2004.',
    'Harry Kane won the Golden Boot at the 2018 men’s World Cup.',
    'England beat Sweden 2-0 in the 2018 World Cup quarter-final.',
    'Kieran Trippier scored England’s free-kick in the 2018 semi-final against Croatia.',
    'England beat Iran 6-2 in their opening match at the 2022 World Cup.',
    'Bukayo Saka scored twice for England against Iran at the 2022 World Cup.'
  ]
};
